# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19vl74BU8bbJFG-7ktt8T-yEWQ81IbPu4
"""

# We use the "raw" version of the GitHub URL to get the actual file content.
!wget https://raw.githubusercontent.com/UniversalDependencies/UD_Naija-NSC/master/pcm_nsc-ud-train.conllu

# Use the 'head' command to show the top part of a file.
# The '-n 500' flag specifies that we want to see the first 500 lines.
!head -n 500 pcm_nsc-ud-train.conllu

import re

# --- Step 1: Define the function (the "recipe") ---
def parse_conllu_for_asr(filepath):
    """
    Parses a CoNLL-U file to extract information needed for ASR.
    **UPDATED to use 'text_ortho' for clean, punctuated transcriptions.**
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    sentences = content.strip().split('\n\n')

    asr_data = []

    for sentence_block in sentences:
        lines = sentence_block.strip().split('\n')

        metadata = {}
        token_lines = []
        for line in lines:
            if line.startswith('#'):
                match = re.match(r'#\s*([^=]+?)\s*=\s*(.*)', line)
                if match:
                    key, value = match.groups()
                    metadata[key.strip()] = value.strip()
            elif line and not line.startswith('#'):
                token_lines.append(line)

        if 'sound_url' in metadata and 'text_ortho' in metadata and token_lines:
            try:
                first_word_misc = token_lines[0].split('\t')[-1]
                start_time = int(re.search(r'AlignBegin=(\d+)', first_word_misc).group(1))

                last_word_misc = token_lines[-1].split('\t')[-1]
                end_time = int(re.search(r'AlignEnd=(\d+)', last_word_misc).group(1))

                transcription = metadata['text_ortho'].strip()

                asr_data.append({
                    "sent_id": metadata.get('sent_id'),
                    "sound_url": metadata.get('sound_url'),
                    "start_ms": start_time,
                    "end_ms": end_time,
                    "transcription": transcription
                })
            except (AttributeError, IndexError):
                # This part is optional, but good for debugging
                # print(f"Skipping block for sent_id: {metadata.get('sent_id')} (missing timing info)")
                continue

    return asr_data

# --- Step 2: Call the function and store the result (the "baking") ---
# This is the line that actually creates the 'prepared_data' variable.
# --- PARSE AND FILTER DATA ---

# 1. Parse the original file (same as before)
conllu_file = 'pcm_nsc-ud-train.conllu'
prepared_data = parse_conllu_for_asr(conllu_file)
original_count = len(prepared_data)
print(f"✅ Step 1: Parsed the file and found {original_count} total potential clips.")


# 2. Apply your filters to create a new, clean list
print("\n✅ Step 2: Applying filters...")
print("   - Removing sentences with '...'")
print("   - Removing sentences with fewer than 4 words.")

filtered_data = [
    item for item in prepared_data
    # Condition 1: The transcription must NOT contain "..."
    if "..." not in item['transcription'] and \
    # Condition 2: The number of words must be 4 or more
       len(item['transcription'].split()) >= 4
]

filtered_count = len(filtered_data)
removed_count = original_count - filtered_count

print(f"\n✅ Filtering complete!")
print(f"   Original items: {original_count}")
print(f"   Items removed:  {removed_count}")
print(f"   Clean items remaining: {filtered_count}")

# From now on, we will use 'filtered_data' for all audio processing.

# --- FINAL, STAGED PIPELINE SCRIPT ---

!pip install -q pydub

import os
import requests
from pydub import AudioSegment
from tqdm.auto import tqdm
import concurrent.futures
import subprocess

# --- Setup Directories ---
os.makedirs("full_mp3s", exist_ok=True)
os.makedirs("full_wavs", exist_ok=True)
os.makedirs("clips", exist_ok=True)

# ==============================================================================
# STAGE 1: DOWNLOAD ALL UNIQUE MP3 FILES
# ==============================================================================
print("--- STAGE 1: Downloading all unique MP3 files ---")

# Get a list of unique URLs to download
unique_urls = sorted(list(set(item['sound_url'] for item in filtered_data)))
print(f"Found {len(unique_urls)} unique MP3 files to download.")

def download_url(url):
    """Downloads a single URL if it doesn't already exist."""
    try:
        base_filename = os.path.basename(url)
        local_mp3_path = os.path.join("full_mp3s", base_filename)
        if not os.path.exists(local_mp3_path):
            response = requests.get(url, timeout=30)
            response.raise_for_status()
            with open(local_mp3_path, 'wb') as f:
                f.write(response.content)
            return f"Downloaded: {base_filename}"
        return f"Skipped (already exists): {base_filename}"
    except Exception as e:
        return f"Failed: {os.path.basename(url)} - {e}"

# Run downloads in parallel
with concurrent.futures.ThreadPoolExecutor(max_workers=8) as executor:
    list(tqdm(executor.map(download_url, unique_urls), total=len(unique_urls)))

print("\n--- Download stage complete. ---\n")


# ==============================================================================
# STAGE 2: CONVERT ALL MP3s TO WAVs
# ==============================================================================
print("--- STAGE 2: Converting all MP3s to WAV format ---")

# Get a list of all downloaded MP3s
mp3_files = [os.path.join("full_mp3s", f) for f in os.listdir("full_mp3s") if f.endswith(".mp3")]
print(f"Found {len(mp3_files)} MP3s to convert.")

def convert_mp3_to_wav(mp3_path):
    """Converts a single MP3 to WAV if the WAV doesn't already exist."""
    try:
        base_filename = os.path.basename(mp3_path)
        filename_no_ext = os.path.splitext(base_filename)[0]
        wav_path = os.path.join("full_wavs", f"{filename_no_ext}.wav")

        if not os.path.exists(wav_path):
            command = ["ffmpeg", "-i", mp3_path, "-y", wav_path, "-loglevel", "error"]
            subprocess.run(command, check=True)
        return f"Converted: {base_filename}"
    except Exception as e:
        return f"Failed to convert: {os.path.basename(mp3_path)} - {e}"

# Run conversions in parallel
with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor: # Use fewer workers for CPU-bound tasks
    list(tqdm(executor.map(convert_mp3_to_wav, mp3_files), total=len(mp3_files)))

print("\n--- Conversion stage complete. ---\n")


# ==============================================================================
# STAGE 3: SLICE ALL CLIPS FROM THE WAV FILES
# ==============================================================================
print("--- STAGE 3: Slicing clips from WAV files ---")

def slice_clip(item_with_index):
    """Slices a single clip from its corresponding WAV file."""
    index, item = item_with_index
    try:
        base_filename = os.path.basename(item['sound_url'])
        filename_no_ext = os.path.splitext(base_filename)[0]
        wav_path = os.path.join("full_wavs", f"{filename_no_ext}.wav")

        audio = AudioSegment.from_wav(wav_path)
        clip = audio[item['start_ms']:item['end_ms']]

        clip_filename = f"pidgin_{index + 1:04d}.wav"
        clip_path = os.path.join("clips", clip_filename)
        clip.export(clip_path, format="wav")
        return (clip_path, item)
    except Exception:
        return None

# Run slicing in parallel
results = []
tasks = list(enumerate(filtered_data))
with concurrent.futures.ThreadPoolExecutor(max_workers=16) as executor:
    future_to_item = {executor.submit(slice_clip, task): task for task in tasks}
    for future in tqdm(concurrent.futures.as_completed(future_to_item), total=len(tasks)):
        result = future.result()
        if result is not None:
            results.append(result)

# --- Final update and count ---
successful_count = 0
for clip_path, original_item in results:
    original_item['audio_filepath'] = clip_path
    successful_count += 1

print(f"\n--- Slicing complete! Successfully generated {successful_count} clips. ---")

import pandas as pd

# 1. Start with the successfully processed, filtered data
final_data = [d for d in filtered_data if 'audio_filepath' in d]

# 2. Check if there is any data
if not final_data:
    print("⚠️ Warning: No data was successfully processed. The manifest file will be empty.")
else:
    # 3. Create a DataFrame from the data
    df = pd.DataFrame(final_data)

    # 4. Create a NEW DataFrame that contains ONLY the 'transcription' column
    transcript_df = df[['transcription']]

    # 5. Save this new DataFrame to a CSV with specific options
    #    header=False tells pandas NOT to write the column name ('transcription')
    #    index=False tells pandas NOT to write the row numbers (0, 1, 2, ...)
    transcript_df.to_csv('transcripts.csv', header=False, index=False)

    print("\n✅ Minimal CSV file 'transcripts.csv' created successfully.")
    print("   It contains only the transcription column with no header.")

    # 6. Show a preview of the new, minimal CSV file
    print("\n--- Here's a preview of your file: ---")
    !head transcripts.csv

import os

# Define the path to your directory
clips_directory = 'clips'

# Check if the directory exists to avoid errors
if os.path.exists(clips_directory):
  # os.listdir() returns a list of all file and directory names
  file_list = os.listdir(clips_directory)

  # The number of files is the length of the list
  num_files = len(file_list)

  print(f"There are {num_files} files in the '{clips_directory}' folder.")
else:
  print(f"The directory '{clips_directory}' does not exist.")

# --- ANALYZE SENTENCE LENGTH DISTRIBUTION ---

# Make sure you are using your final, clean dataset
# If you haven't run the filtering step, you might want to use 'prepared_data' instead.
try:
    data_to_analyze = filtered_data
except NameError:
    print("❌ Error: The 'filtered_data' variable is not defined. Please run the filtering step first.")
    # You could fall back to the original data if you want:
    # data_to_analyze = prepared_data
    data_to_analyze = [] # Or just stop

# Proceed only if there is data to analyze
if data_to_analyze:
    # 1. Define the word count thresholds you want to check
    word_count_thresholds = [5, 6, 7, 8, 9]

    # 2. Initialize a dictionary to store the counts for each threshold
    #    This creates a dictionary like: {5: 0, 6: 0, 7: 0, ...}
    sentence_stats = {threshold: 0 for threshold in word_count_thresholds}

    # 3. Loop through every item in your dataset
    for item in data_to_analyze:
        # Get the sentence and count the words by splitting on spaces
        transcription = item['transcription']
        word_count = len(transcription.split())

        # 4. Check the word count against each of your thresholds
        for threshold in word_count_thresholds:
            if word_count > threshold:
                # If it's greater, increment the counter for that threshold
                sentence_stats[threshold] += 1

    # --- 5. Print the results in a nicely formatted table ---
    total_sentences = len(data_to_analyze)
    print(f"Analyzing a total of {total_sentences} sentences...\n")
    print("--- Sentence Length Statistics ---")

    for threshold, count in sentence_stats.items():
        # Calculate the percentage for better context
        percentage = (count / total_sentences) * 100 if total_sentences > 0 else 0

        # The formatting {:5d} adds padding to align the numbers nicely
        print(f"Sentences with MORE THAN {threshold} words: {count:5d} ({percentage:.2f}%)")
else:
    print("⚠️ No data to analyze.")

import os
import zipfile
from tqdm.auto import tqdm # For a nice progress bar

# Define the folder to zip and the name of the output zip file
folder_to_zip = 'clips'
zip_filename = 'clips_python.zip'

# Get the list of files to add to the zip
# This ensures we don't try to zip a folder that doesn't exist
try:
    file_paths = [os.path.join(folder_to_zip, f) for f in os.listdir(folder_to_zip)]
except FileNotFoundError:
    print(f"Error: The folder '{folder_to_zip}' was not found.")
    file_paths = []

if file_paths:
    print(f"Zipping {len(file_paths)} files from '{folder_to_zip}' into '{zip_filename}'...")

    # Create a new zip file in write mode
    with zipfile.ZipFile(zip_filename, 'w') as zipf:
        # Loop through the files, showing a progress bar
        for file in tqdm(file_paths):
            # The 'arcname' parameter prevents the folder structure ('clips/')
            # from being stored in the zip file, storing just the filename.
            zipf.write(file, arcname=os.path.basename(file))

    print("\n✅ Zipping complete!")
    print(f"File '{zip_filename}' has been created.")

import os

zip_filename = 'clips_python.zip'

if os.path.exists(zip_filename):
    file_size_bytes = os.path.getsize(zip_filename)

    # Convert to more human-readable units
    if file_size_bytes < 1024:
        size_display = f"{file_size_bytes} bytes"
    elif file_size_bytes < 1024 * 1024:
        size_display = f"{file_size_bytes / 1024:.2f} KB"
    else:
        size_display = f"{file_size_bytes / (1024 * 1024):.2f} MB"

    print(f"The size of '{zip_filename}' is: {size_display}")
else:
    print(f"Error: The file '{zip_filename}' was not found.")

from google.colab import drive
drive.mount('/content/drive')

"""Once your Google Drive is mounted, run the next cell to copy the `clips` folder to your Drive. The command `cp -r` is used to recursively copy directories."""

!cp -r clips /content/drive/MyDrive/

"""The `clips` folder has been copied to your Google Drive. You should now see it in your 'My Drive' folder."""